services:
  - type: web
    runtime: python
    name: movie-app
    buildCommand: ./build.sh
    startCommand: uv run gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
