services:
  - type: web
    runtime: python
    name: aster-app
    buildCommand: ./build.sh
    startCommand: uv run gunicorn config.wsgi:application
    healthCheckPath: /health/
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: DJANGO_ADMIN_URL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
