# Generated by Django 5.2.13 on 2026-05-01 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "follow",
                "verbose_name_plural": "follows",
                "indexes": [
                    models.Index(
                        fields=["follower", "-created_at"],
                        name="community_f_followe_71cac1_idx",
                    ),
                    models.Index(
                        fields=["followee", "-created_at"],
                        name="community_f_followe_1e3195_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("follower", "followee"), name="uq_follow_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("follower", models.F("followee")), _negated=True
                        ),
                        name="ck_follow_not_self",
                    ),
                ],
            },
        ),
    ]
