# Generated by Django 5.2.12 on 2026-04-12 09:35

from decimal import Decimal

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rating",
            name="ck_rating_score_1_5",
        ),
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.5")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
                verbose_name="Ocena",
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score__gte", Decimal("0.5")), ("score__lte", Decimal("5.0"))
                ),
                name="ck_rating_score_half_5",
            ),
        ),
    ]
