# Generated by Django 5.2.12 on 2026-04-12 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_half_star_ratings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True, verbose_name="TMDB id")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "profile_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Profile image URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MovieCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[("cast", "Aktor"), ("director", "Reżyser")],
                        max_length=20,
                        verbose_name="Credit type",
                    ),
                ),
                (
                    "character",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Character"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Billing order")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="movies.movie",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="movies.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "movie credit",
                "verbose_name_plural": "movie credits",
                "ordering": ["order"],
                "indexes": [
                    models.Index(
                        fields=["movie", "credit_type", "order"],
                        name="movies_movi_movie_i_d005f5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("movie", "person", "credit_type"),
                        name="uq_movie_person_credit",
                    )
                ],
            },
        ),
    ]
