# Generated by Django 5.2.13 on 2026-04-29 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_person_and_credits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["user", "score"], name="movies_rati_user_id_4e1bc6_idx"
            ),
        ),
    ]
