# Generated by Django 5.2.13 on 2026-05-01 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0008_rating_movies_rati_user_id_4e1bc6_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["user", "-created_at"], name="movies_rati_user_id_d94fb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermoviestatus",
            index=models.Index(
                fields=["user", "status", "-updated_at"],
                name="movies_user_user_id_b4cc50_idx",
            ),
        ),
    ]
